/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザー登録 */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ユーザー更新 */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/v1/user/{user_id}/charge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** チャージ */
        post: operations["chargeAmount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/{user_id}/charge/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** チャージキャンセル */
        post: operations["chargeCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/{user_id}/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 購入 */
        post: operations["createPurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/{user_id}/purchase/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 購入キャンセル */
        post: operations["cancelPurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/{user_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 残高取得 */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user/{user_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 購入履歴取得 */
        get: operations["getPurchaseHistories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全商品取得 */
        get: operations["getAllItems"];
        put?: never;
        /** 商品登録 */
        post: operations["registerItem"];
        delete?: never;
        options?: never;
        head?: never;
        /** 商品更新 */
        patch: operations["updateItem"];
        trace?: never;
    };
    "/v1/item/{jan_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** JANコードで商品取得 */
        get: operations["getItemByJanCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PostUserRequest: {
            /** @description ユーザーID */
            user_id: string;
            /** @description ユーザー名 */
            user_name: string;
        };
        PatchUserRequest: {
            /** @description ユーザー名 */
            user_name: string;
        };
        PostChargeRequest: {
            /**
             * @description チャージ金額（500, 1000, 2000 のいずれか）
             * @enum {integer}
             */
            amount: 500 | 1000 | 2000;
        };
        PostChargeCancelRequest: {
            /**
             * @description キャンセル金額（500, 1000, 2000 のいずれか）
             * @enum {integer}
             */
            amount: 500 | 1000 | 2000;
        };
        PostItemRequest: {
            /** @description JANコード（8桁または13桁） */
            jan_code: string;
            /** @description 商品名 */
            item_name: string;
            /** @description 価格 */
            price: number;
        };
        PatchItemRequest: {
            /** @description JANコード（8桁または13桁） */
            jan_code: string;
            /** @description 商品名 */
            item_name: string;
            /** @description 価格 */
            price: number;
        };
        PurchaseItem: {
            /** @description 商品ID */
            item_id: number;
            /** @description 数量 */
            quantity: number;
        };
        PostPurchaseRequest: {
            items: components["schemas"]["PurchaseItem"][];
        };
        PostPurchaseCancelRequest: {
            items: components["schemas"]["PurchaseItem"][];
        };
        PostUserResponse: {
            /** @example success */
            status?: string;
            user_id?: string;
            user_name?: string;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            created_at?: string;
        };
        PatchUserResponse: {
            /** @example success */
            status?: string;
            user_id?: string;
            user_name?: string;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            created_at?: string;
        };
        ChargeResponse: {
            /** @example success */
            status?: string;
            charge_id?: number;
            charge_amount?: number;
            user_id?: string;
            balance?: number;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            created_at?: string;
        };
        ChargeCancelResponse: {
            /** @example success */
            status?: string;
            charge_id?: number;
            canceled_amount?: number;
            user_id?: string;
            balance?: number;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            created_at?: string;
        };
        PostItemResponse: {
            /** @example success */
            status?: string;
            id?: number;
            jan_code?: string;
            item_name?: string;
            price?: number;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            updated_at?: string;
        };
        PatchItemResponse: {
            /** @example success */
            status?: string;
            id?: number;
            jan_code?: string;
            item_name?: string;
            price?: number;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            updated_at?: string;
        };
        GetItemResponse: {
            /** @example success */
            status?: string;
            item_id?: number;
            jan_code?: string;
            item_name?: string;
            price?: number;
        };
        GetAllItemsResponse: {
            /** @example success */
            status?: string;
            items?: {
                item_id?: number;
                jan_code?: string;
                item_name?: string;
                price?: number;
            }[];
        };
        PostPurchaseResponse: {
            /** @example success */
            status?: string;
            /** @description 残金 */
            balance?: number;
            user_id?: string;
            items?: components["schemas"]["PurchaseItem"][];
        };
        PostPurchaseCancelResponse: {
            /** @example success */
            status?: string;
            id?: number;
            user_id?: string;
            items?: components["schemas"]["PurchaseItem"][];
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            created_at?: string;
        };
        GetBalanceResponse: {
            /** @example success */
            status?: string;
            user_id?: string;
            balance?: number;
        };
        HistoryItem: {
            item_name?: string;
            quantity?: number;
            price?: number;
            /**
             * Format: date-time
             * @example 2025-01-01T00:00:00.000Z
             */
            purchase_at?: string;
        };
        PageInfo: {
            /** @description 前のページ番号（存在しない場合は省略） */
            prev_page?: number | null;
            /** @description 次のページ番号（存在しない場合は省略） */
            next_page?: number | null;
            /** @description 総ページ数 */
            total_page?: number;
        };
        GetPurchaseHistoriesResponse: {
            /** @example success */
            status?: string;
            histories?: components["schemas"]["HistoryItem"][];
            /** @description 合計金額 */
            total?: number;
            page?: components["schemas"]["PageInfo"];
        };
        ErrorResponse: {
            /** @example error */
            status?: string;
            /** @description エラーメッセージ */
            message?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description ユーザーID */
        UserId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostUserRequest"];
            };
        };
        responses: {
            /** @description 登録成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostUserResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchUserResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chargeAmount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostChargeRequest"];
            };
        };
        responses: {
            /** @description チャージ成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chargeCancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostChargeCancelRequest"];
            };
        };
        responses: {
            /** @description キャンセル成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeCancelResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostPurchaseRequest"];
            };
        };
        responses: {
            /** @description 購入成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPurchaseResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostPurchaseCancelRequest"];
            };
        };
        responses: {
            /** @description キャンセル成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPurchaseCancelResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetBalanceResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPurchaseHistories: {
        parameters: {
            query?: {
                /** @description ページ番号 */
                page?: number;
                /** @description 1ページあたりの件数 */
                per_page?: number;
            };
            header?: never;
            path: {
                /** @description ユーザーID */
                user_id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPurchaseHistoriesResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAllItems: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAllItemsResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostItemRequest"];
            };
        };
        responses: {
            /** @description 登録成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostItemResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchItemRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchItemResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getItemByJanCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description JANコード（8桁または13桁） */
                jan_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetItemResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバーエラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
